apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-playground
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-curl-to-hello
  namespace: istio-playground
spec:
  selector:
    matchLabels:
      app: hello
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-playground/sa/default
